language: java
jdk:
  - oraclejdk7
  - openjdk7

sudo: false

cache:
  directories:
    - $HOME/.m2

install:
  - mvn package -P all-modules dependency:resolve -Dmaven.test.skip -Dmaven.javadoc.skip -Dcassandra.skip

script: 
  - mvn verify -Pcassandra-2.0 -Dmaven.javadoc.skip --quiet

after_success:
  - mvn jacoco:report jacoco:report-integration coveralls:report

before_deploy: "echo 'ready to deploy?'"

deploy:
  skip_cleanup: true
  provider: releases
  api_key: 
    secure: Eue8cRnapBQim2wArFkR88r+SJHe4Qs5gcor8QCWJuFltJcRG7JCu+y7FAjeYSCBqXGNVENirRjV5YnfdQS4uNKhb3m3WalneJDGCUtk82VdeJiNwV52IjKJEmpTUQu+bun1aoU0+ZY2PkzFW8S1lpCzj+n/YH3LWgIiXayiOhOzL2Yq1VJp2/BVnEZvKRpVlN55SwFPTkWVta2qKpr0b7KfNpPLQArQqJUExrHMQxFb2iM1Yb0xp2C2HQIYSr3xYw9eR5TjFI2NEZwfzhsrJ5M/ZVbkM5UAOranHGiQvJ2Eha8o0XHqvjOCPcJUVXJ7M9+xRA5THMVBrLCMZOH9LIskwHQxx9318b1jfw2uM+fwEZwqfyakCN/pmaQFxzzBmVDsFwlkoqzYIRimanOlLhwyNY9Nkc0XN40ksvIdmIoG0llOtZFQf168WsWUT5GR1QQrNe1sAgWdPQ51suxEcL0HITwlna4VUakdbNxBZjZ5+//pTMohH5aWlkJSt+4oJIsq0tUpDonGQ7pJ9iR12cISiXmjBAEFDKtPM2JJsBuP73kLmgHS11lUY0sFtz5oyR9NjBr2Gjrs15XCFqZwn21SiTzunHo9e3k2oiU74g3B7UZ+YiiKRhnv5gTu7Gps4MgpVlIsOPU4h9ygZQJga2odoJKKMMFQlyCsGHyo54U=
  file_glob: true
  file:
    - "./blueflood-all/target/blueflood-all-2.0.0-SNAPSHOT-jar-with-dependencies.jar"
  on:
    repo: goru97/blueflood
    tags: true
    branch: release
