language: java
jdk:
  - oraclejdk7
  - openjdk7

sudo: false

cache:
  directories:
    - $HOME/.m2

install:
  - mvn package -P all-modules dependency:resolve -Dmaven.test.skip -Dmaven.javadoc.skip -Dcassandra.skip

script: 
  - mvn verify -Pcassandra-2.0 -Dmaven.javadoc.skip --quiet

after_success:
  - mvn jacoco:report jacoco:report-integration coveralls:report

deploy:
  skip_cleanup: true
  provider: releases
  api_key: 
    secure: "br9Zc1bZtOL4AZ5UZsuB2LwJcAd9dgEdyPD+CMUDb3G6UvcQ+PG14+eB+rfp3/UXAK3UeemMBcm6DEBdTXtNJJKQBdE3HgFRt9rMd8IJHzFPf70WVcrVTWwx2WQB0JGUJiTLkBTHW4gOXEjS1SCEbmSIsDAt0LjP9ESUqEw4UVXSNK31qrZgGskaNhLs1T0UJFJzp6FwJ0WOyzkY8sxZxJyywo+8bvSAM7zkSzn0KXd/SEPoikilBZdLRq9AKgAtpAAGms9q0f1JH9/PxJ7BoNjUnLvvhdOxAcXssQuiJZVBS5CzKKs65/xFZxBcaFwYPQpc8Q5k54tHwmU5JLg8re5uBdjhOJ9njQ5hldx5oriU/VkDbIYR/bQqN378inwb72NShD0mH10ofoLK0jPXD8titMFbbqQSEoOpkp/6vIqPfwdM0yi5lsasU1pnhZ0xqDZWtYNsG+D5OdyIfVbjd5JAUJCRPMpGXuckWheV9NDjLIXpZ9rSzufy7jeRR7OFr24/yJnxGtEYdNN/Fjw4Cv6wO/eND4GC43Pu3brwXQJHLrtItousNlOUDEoh1NMbgFLm0eqsCq8I9o0oLm0VtTDCGH7Yi7g2gMFLiaTw+ZpztPN/gF+hbtMR556tpd7wXHSngy52HxAFJ52XjoxnxAP3vp1c6cXPDCQv69D4WIM="
  file:
    - "./blueflood-all/target/blueflood-all-2.0.0-SNAPSHOT-jar-with-dependencies.jar"
  on:
    tags: false
    branch: release
