language: java
jdk:
  - oraclejdk7
  - openjdk7

sudo: false

cache:
  directories:
    - $HOME/.m2

install:
  - mvn package -P all-modules dependency:resolve -Dmaven.test.skip -Dmaven.javadoc.skip -Dcassandra.skip

script: 
  - mvn verify -Pcassandra-2.0 -Dmaven.javadoc.skip --quiet

after_success:
  - mvn jacoco:report jacoco:report-integration coveralls:report

deploy:
  skip_cleanup: true
  provider: releases
  api_key: a6b022145171db0abb1eb5c703dabd4f529d42c7
  file:
    - "./blueflood-all/target/blueflood-all-2.0.0-SNAPSHOT-jar-with-dependencies.jar"
  on:
    tags: false
    branch: release
